# Generated by Django 3.0.3 on 2020-03-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Mobiles', 'mobiles'), ('Laptops', 'laptops'), ('Tablets', 'tablets'), ('Tvs', 'tvs'), ('Accessories', 'accessories')], max_length=100)),
                ('sub_name', models.CharField(max_length=150)),
            ],
        ),
    ]
